version: '3'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - node_app
    networks:
      - app-network

  node_app:
    build:
      context: ./cat-hub/app/api
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge